### ISSUE TITLE
Lens names are not consistent between in camera CR3 and JPG files and converted DNG files 

### ISSUE THREAD

**Issue by arbv** [dnglab/dnglab#173]
The lens names in converted DNGs are not the same as in-camera files (both CR3s and JPGs). That imposes compatibility issues between tools, relying on metadata for detecting proper lens correction profile (LCP).

I have used `dnglab` executable built straight out of the current master branch.

In particular, in the case of `Canon EF-S 17-55mm f/2.8 IS USM`:

* the lens is named as `EF-S17-55mm f/2.8 IS USM` in JPGs and CR3 files' metadata (Lens maker is **not defined**);
* the lens is named as `EF-S 17-55mm f/2.8 IS USM` in converted DNG files (Lens maker is defined as `Canon`).

When files are being converted with Adobe RAW Convereter, such a problem does not arise.

That is a big compatibility issue in the long run, which is better to be fixed ASAP, while software is in the alpha state. Such an incompatibility defeats the purpose of using DNG, which is a RAW format intended for archival purposes.

The tool should not modify the original lens names, nor add the tags non-present in the original files (e.g. Lens Maker)

Example files can be downloaded using the following [link](https://mega.nz/file/mksnDDwB#irwXriPqDLNbdOOLiem9WLICywYYSe_tLOJd6Kh5KVU). The archive contains CR3, in camera JPG, and a DNG file.

**Comment by arbv** [comment]
FYI, as an extra step for now, I use `exiftool` to preserve the original tags as found in the raw file, like follows:

```
exiftool -overwrite_original_in_place -all= -tagsFromFile input.cr3 output.dng
```

The command removes all tags from the DNG (`-all=`) and copies the tags from the raw file. The tool takes care of the metadata extraction.

That seems to work fine.

**Comment by cytrinox** [comment]
That's a feature.

Most raw formats only includes an identifier (like an integer or 8 bytes in case of Nikon) for the used lens. But DNG don't know anything about lens IDs, you have to provide a lens make and model. Only some newer raw formats like CR3 has an internal string where a lens name can be found (and of course the lens integer identifier). But this is not the official name used by the manufacturer and sometimes contains additional data like revision codes. This is also the case for Canon.

So yes, there is a lens name in CR3 but it is not relevant for the population of the specific DNG tags. The main goal is to use model names matching the exiv2 and exiftool lens definitions, because these projects are the relevant libraries used in FOSS projects like Darktable and RawTherapee, especially in the lensfun library providing calibration profiles. It should be always forced to have working lens autodetection for dnglab DNGs in Darktable and RT via libfun. If not, this should be considered as a bug.
Whatever Adobe does or does not for their DNGs is of less relevance.

I can't currently test this, but if you attach your EF-S 17-55 lens to an old Canon model like 5D (whatever camera generates CR2) and convert this file with Adobe DNG, the embedded lens name is something different from "EF-S17-55mm f/2.8 IS USM", because these names without the space first introduced in CR3. And dnglab also populates tags like LensSpec correctly which isn't true for Adobe DNG.

I prefer a solution where all DNGs for Raws with a specific lens but different camera bodies should contain identical lens tags and that is how it is currently implemented. You even get the identical names when using a Sigma lens made for EF mount and the same for Nikon mount.

**Comment by arbv** [comment]
@cytrinox Thanks for these insides! Very appreciated.

I will change my "Dynamic Rules" within RawTherapee to use regular expressions to match Canon lenses then.

It is such a pain in the neck that there are some incompatibilities even when a relatively open format (DNG) is involved.
