### ISSUE TITLE
Canon R50 support

### ISSUE THREAD

**Issue by cytrinox** [dnglab/dnglab#309]
Samples needed.

**Comment by cytrinox** [comment]
@laemplein I've seen your issue https://github.com/darktable-org/darktable/issues/14574 on darktable. Maybe you can provide a set of R50 samples, please?  See https://github.com/dnglab/dnglab/blob/main/CONTRIBUTE_SAMPLES.md#canon-cr3 for what samples are required.
Thank you.

**Comment by laemplein** [comment]
Hei, sorry this took a little longer because I had to get my hands on another R50. I took the files as described and uploaded them here:

https://segel-fotografie.de/cloud/index.php/s/R5ibesmzAMQNYRa

The camera only shoots HEIF in HDR mode I think. I have uploaded these together with their RAW and cRAW files.

About DualPixel: I don't see an option to save this in the RAW files?

Please let me know if I can help out with anything more. Thank you for your time!
Sven

**Comment by cytrinox** [comment]
Awesome, thanks!

I've checked the files: The Burst_1..2..3.. files are shoot with high speed shutter or something else? The R50 has no support for Burst Mode (multiple shoots in a single CR3 file) according to the manual.

I've found another new feature in R50 manual: it supports digital teleconverter: https://cam.start.canon/de/C011/manual/html/UG-05_Shooting-1_0050.html
Can you please shoot a sample for 2x and 4x (RAW and CRAW for each), then the set would be complete.

Dual Pixel is not supported on R50.

@lclevy FYI.

**Comment by laemplein** [comment]
Hei, yes the Burst files were shot in Burst drive mode (the fastest available). I didn't knew that there is something else available (I am not a Canon shooter). I will delete these files right away to keep the size down.

About the teleconverter: it is greyed out as soon as a RAW or cRAW quality is selected (even in companion with JPEG files). So I guess this is only a JPEG crop and does not affect RAW files at all.
