### ISSUE TITLE
Extract of Canon RAW Burst Mode contents direct to RAW files?

### ISSUE THREAD

**Issue by vvpeter** [dnglab/dnglab#353]
Is there an option you can add that will output RAW files from the Canon burst mode file?  Canon's DPP app doesn't support DNG files, and having that option would let it be done in a single step.

**Comment by cytrinox** [comment]
Already exists.

`--image-index all --embed-raw false`

Extracts all frames in RawBurst as separate DNGs.

**Comment by vvpeter** [comment]
I already tried that, and as I said, the Canon Digital Photo Professional Windows app can't open DNG files unfortunately.  So I need them just as RAWs, not DNG w/an embedded RAW.  And even w/the embedding, it looks like the entire set of burst images is included w/each DNG, not just the 1 associated w/each DNG frame.

**Comment by PeterWem** [comment]
CR3 is Canon file format. I don't think any third-party software will write CR3.

**Comment by bwfisher82** [comment]
The software obviously can extract the RAW CR3 from the roll file in order to covert each one to DNG. What's being asked is a feature to just covert the CR3 roll to CR3 singles but not also convert them to DNG at the same time. I would also love this feature. The biggest issue I have with Canon workflow is their own software's inability to do this (you have to extract one frame at a time). I don't always want to work with DNGs so this would be a really helpful feature. I can covert the singles to DNGs with the tool if I want to later on.

**Comment by cytrinox** [comment]
CR3 rolls can only extracted into single DNG files, CR3 write-support is not available and not planned.
