### ISSUE TITLE
Extracting RAW Images from Canon Raw Burst Mode file (CSI prefix, .CR3 extension) doesn't set output DNG image previews correctly

### ISSUE THREAD

**Issue by carsongmiller** [dnglab/dnglab#447]
When you extract DNG's from a canon raw burst mode file, each of the resulting DNG's has the same image preview attached to it--the preview of the original CR3 file.  This means that in lightroom, in the library module it doesn't show the actual image--just the incorrect preview.  This is also true in the develop module for a few seconds before loading each image as you flip through them, and in windows explorer.

This makes using DNGLab to do this task much less useful.  Would be great if there was a way to generate a new preview image for each output DNG so that each DNG's preview represents it correctly

**Comment by Gendra13** [comment]
Hi,
what command line options do you use? I assume `--image-index all --embed-raw false`.

Did you try including `--dng-preview false --dng-thumbnail false`?
For my test images it seems to fix this issue because then lightroom is forced to create the preview image on its own.

Unfortunatly I currently don't have access to a R7 oder R6II and the test files I have here are without much "action" between the single images.
Would it be possible to share a .cr3 testfile where there is an obvious difference between the embedded images?

**Comment by carsongmiller** [comment]
Interesting idea, but I just tried it and unfortunately it doesn't give me the results I'm looking for.  Now when looking at photos using the built in photos app on windows, it does indeed load the full DNG.  But importing those same new DNG's into lightroom yields the same behavior as before: in the library module, the images all look identical, and in the develop module, when you flip to an image it initially shows the image preview of the first shot in the roll, then switches to the actual DNG after a second or two.  Not a great experience, and I'd rather actually just extract individual images in-camera, since that actually seems to be the lowest-pain option.

If you do want a test raw burst mode image to test with (from a Canon R8), [here is a google drive link to one](https://drive.google.com/file/d/1t-K28ddFx3j5bYGzOkX1MvalBFo2I9-m/view?usp=drive_link).

**Comment by carsongmiller** [comment]
Oh so did you actually get it work work in lightroom where I did not?

Yeah, I really do think at this point just selecting candidates in-camera is the way to go.  It's really not much of a hassle.  But definitely ridiculous that Canon _does_ give a software solution but that it sucks this bad.

**Comment by TsunamiMommy** [comment]
It's DNGlab's fault. It is exporting the wrong preview. Most thumbnail generators uses the `PreviewImage` tag to generate the thumbnails. That preview image is incorrect. DNG lab is only using the initial preview from the roll rather than generating it for each exported dng. I exported the individual previews using exiftool. So neither the `PreviewImage` tag nor the `ThumbnailTIFF` tag uses the correct image.

**Comment by TsunamiMommy** [comment]
A workaround I'm currently using in linux is that I created a new thumbnailer that correctly generates previews from the file itself rather than simply working with the preview images embedded in the file. Perhaps you could insert the correct preview image by using an external conversion tool like `darktable-cli`. You can then properly generate the previews from the exported dng and embed them so that way you always get the correct preview. This can probably happen at the generation stage so I wouldn't have to generate the correct thumbnails on the system side. It'll take a little bit longer but it would ensure correctness with regard to the preview function.

**Comment by TsunamiMommy** [comment]
Okay some additonal information. To correctly generate the previews for each dng the correct exif tag to extra is `JpgFromRaw`. Since there is only one preview for the roll in `PreviewImage` and `ThumbnailImage` these are only the global previews and not relevant for the preview of each extracted raw file. So the JpgFromRaw tags represent each embedded raw file preview in sequence of the order in which the raws were taken. I confirmed this by using exiftool to extract the preview tags from each camera roll file. I'm currently working on building the function into my own secondary conversion tool but it should be something well within the scope of this project to correct.

**Comment by cytrinox** [comment]
This is improved in [e2c44dd](https://github.com/dnglab/dnglab/commit/e2c44dd8bb47fd93fed58c06a8aeb2b7e962c7ea), missing preview&thumbnails are generated from raw pixels.
