### ISSUE TITLE
Canon EF 24-015 f4L, 72-200 f2.8L and with 2x tele not auto detected in raw processing software after dng conversion

### ISSUE THREAD

**Issue by RogerD-AZ** [dnglab/dnglab#498]
Included in the files for download are Canon 24-105 f4L, 70-200 f2.8L and 70-200 f2.8L with 2x tele vIII. All the cr2 and cr3 files auto detect lens in adobe camera raw works as expected, none of them are detected once converted to dng. I'm not sure how to confirm if these are already supported or need to be added, I'm assuming they are already as they are old popular lenses, if yes, is there an issue during converting or? Thank you, Roger

WeTransfer Link:
https://we.tl/t-Kzzh6sPv9j

**Comment by cytrinox** [comment]
These lenses are recognized and correctly written to DNG:

````
  21403778 | 0xa432 LensSpecification            |  RATIONAL |        4 |  21403408 | 24/1 105/1 4/1 4/1
  21403790 | 0xa433 LensMake                     |     ASCII |        6 |  21403440 | Canon
  21403802 | 0xa434 LensModel                    |     ASCII |       27 |  21403448 | EF 24-105mm f/4L IS II USM
  21403814 | 0xa435 LensSerialNumber             |     ASCII |       11 |  21403476 | 5720002455
````

In darktable, I can open these files with proper lens detection with lensfun. 

But I know, lens detection is totally broken in open source and commercial software. Afaik, Adobe software expects the maker to be part of the model - but not for all cameras. For example, in Fuji RAF files, the lens model is always written without the make. There is no standard for proper lens information and even little differences like extra whitespace may broke detection. This is nothing I can fix in dnglab, it needs to be fixed in raw processing software. Keep in mind that in many raw formats, the lens information is only encoded as a numeric lens identifier which conflicts with the DNG requirement to provide a LensMake and LensModel. This adaption (done by dnglab) may or may not work properly for your favorite raw processing software.

**Comment by RogerD-AZ** [comment]
If you don't mind helping me understand better. If the original cr2/3 files are recognized in all the raw processing software I test with, but most do not with the converted dng wouldn't that indicate there is some id information in the cr* that is not being copied to the dng that could/should be?

Is this possibly a hint of what's happening, when I rename the cr3 using meta information to include the lens it renames to...
6053_EF70-200mm f_2.8L IS II USM.CR3 (lens info is auto detected)
... but the rename of the converted to dng is...
6053_EF70-200mm f_2.dng (lens info is not detected)
... it has truncated "8L IS II USM"

I noticed this truncated naming in all that isn't detected. I do acknowledge some software is able to auto detect the dng's, but most can not clearly supporting how to id a lens isn't as standard as it probably should be. 

Very much appreciate your time.. thank you.
